//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHER
    {
        public int MaVoucher { get; set; }
        public string TenVoucher { get; set; }
        public Nullable<int> GiamToiDa { get; set; }
        public Nullable<int> DHToiThieu { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<double> SoTienGiam { get; set; }
        public string Mota { get; set; }
    }
}
